//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoodleDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB_42039_doodleEntities : DbContext
    {
        public DB_42039_doodleEntities()
            : base("name=DB_42039_doodleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<draw> draws { get; set; }
        public virtual DbSet<drawCategory> drawCategories { get; set; }
        public virtual DbSet<drawPoint> drawPoints { get; set; }
        public virtual DbSet<drawStatu> drawStatus { get; set; }
        public virtual DbSet<noodler> noodlers { get; set; }
        public virtual DbSet<userLogin> userLogins { get; set; }
        public virtual DbSet<user> users { get; set; }
    
        public virtual ObjectResult<sp_GatherOpenDraws_Result> sp_GatherOpenDraws()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GatherOpenDraws_Result>("sp_GatherOpenDraws");
        }
    }
}
