//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoodleDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class drawPoint
    {
        public int DrawPointID { get; set; }
        public Nullable<int> DrawID { get; set; }
        public Nullable<double> DrawPointX { get; set; }
        public Nullable<double> DrawPointY { get; set; }
    
        public virtual draw draw { get; set; }
    }
}
