//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoodleDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class drawCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public drawCategory()
        {
            this.draws = new HashSet<draw>();
        }
    
        public int DrawCategoryID { get; set; }
        public string DrawCategoryName { get; set; }
        public string DrawCategoryIcon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<draw> draws { get; set; }
    }
}
