//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoodleDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class noodler
    {
        public int DrawNoodlerID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> DrawID { get; set; }
        public Nullable<bool> Winner { get; set; }
        public Nullable<int> DrawRating { get; set; }
        public Nullable<int> DoodlerRating { get; set; }
    
        public virtual draws draw { get; set; }
        public virtual user user { get; set; }
    }
}
